apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app
  name: springboot-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      volumes:
      - name: hostpathvol
        hostPath:
          path: /tmp/mongodb 
      containers:
      - name: my-springboot-app
        image: public.ecr.aws/g7r5s0z3/expressappcontainer:${pomversion}
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        volumeMounts:
        - name: hostpathvol
          mountPath: /data/db
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
spec:
  type: NodePort
  selector:
     app: springboot-app
  ports:
  - port: 80
    targetPort: 8080
