apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      volumes:
      - name: hostpathvol
        hostPath:
          path: /tmp/mongodb 
      containers:
      - name: my-springboot-app
        image: yoshithadocker/mydockerrepo:17
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        volumeMounts:
        - name: hostpathvol
          mountPath: /data/db
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9090
  type: LoadBalancer
  selector:
    app: springboot-app
